services:
  - type: web
    name: anchora-api
    env: node
    buildCommand: cd api && npm install && npx prisma generate
    startCommand: cd api && npm start
    
  - type: web
    name: anchora-app
    env: static
    buildCommand: cd app && npm install && npm run build
    staticPublishPath: app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

